// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/snack-ladder-power-tray/ClearLabels.tsx": () => import("../components/mockups/snack-ladder-power-tray/ClearLabels.tsx"),
  "./components/mockups/snack-ladder-power-tray/Current.tsx": () => import("../components/mockups/snack-ladder-power-tray/Current.tsx")
};
